name: Docker Compose CI test

on:
  workflow_dispatch:      

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rename target compose file
      run: mv docker-compose.dev.yml docker-compose.yml
      
    - name: Rename development env file
      run: mv ./server/.env.dev-sample ./server/.env.dev
    
    - name: list files
      run: ls -a
    
    - name: Build the Docker-compose file
      run: docker-compose -f "docker-compose.yml" up -d --build
