name: Docker Compose CI

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker-compose file
      run: docker-compose up 
